import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Gelatinous dice</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Gelatinous dice</h1>
      </main>

      <footer className={styles.footer}>
        <div className={styles.row}>
          <p>Created by</p>
          <a className={styles.link} href="https://github.com/ChuckLeon/" target="_blank" rel="noreferrer noopener"> Charles Héon</a>
        </div> 
      </footer>
    </div>
  );
}
